security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # Define your custom user provider here if you have one
        app_user_provider:
            memory:
                users:
                    test@example.com: { password: '$2y$10$sZI624e3zOykSQm.1A8/te6gQj8pY0t23s1IL05amnQTxbMnPlyrC', roles: ['ROLE_USER'] }
                    # Add more users as needed
                    # user2: { password: ..., roles: [...] }
    
    enable_authenticator_manager: true
    # ...

    firewalls:
       
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
