security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # Define your custom user provider here if you have one
        app_user_provider:
            memory:
                users:
                    user1: { password: '$argon2id$v=19$m=65536,t=4,p=1$Vl8yZlBWU3NsT3JvSjlQeg$Ud/pF1ZjPZpw9rG0yq/gFwlZgsZm8d5YHDgNhzIg4eI', roles: ['ROLE_USER'] }
                    # Add more users as needed
                    # user2: { password: ..., roles: [...] }
    
    enable_authenticator_manager: true
    # ...

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
